### ISSUE TITLE
How to convert the generated img to real transparent img?

### ISSUE THREAD

**Issue by zengjie617789** [layerdiffusion/sd-forge-layerdiffusion#31]
Thanks for the great work. It seems the generated img isnot real img with transparent background, instead a background with chessboard. I want to replace the corrsponding pixel by photoshop, but it failed. I want to know to how to implement to get a img with a transparent channel.

**Comment by layerdiffusion** [comment]
the transparent image is next to the checkboard image

**Comment by magejosh** [comment]
Not when i generate them. Is it possible having an alternative output dir prevents saving of the transparent background version?

**Comment by protector131090** [comment]
> Not when i generate them. Is it possible having an alternative output dir prevents saving of the transparent background version?

have the same problem. My transparent PNGs go to %temp% folder for some reason... trying reinstalling course if you use batch size diferent from 1 they wont save at all...

**Comment by protector131090** [comment]
> the transparent image is next to the checkboard image

Except there arent any. Transparent Image goes to temp folder but if batch is more than 1 it wont save at all

**Comment by protector131090** [comment]
clean install of forge didnt do anything. Still the same result. to outputs saved with checkerboard and to temp/gradio is the one transparent....

**Comment by victorca25** [comment]
@layerdiffusion there is a small error in the concatenation of the checkerboard image and the transparent image in the "patch()" function in models.py.

I noticed it's not only that the wrong image is being saved to the output directory, but also that ADetailer is applied to the wrong image :)

A quick patch for anyone who wants to avoid too many complications while this is fixed, you can change this line: https://github.com/layerdiffusion/sd-forge-layerdiffuse/blob/e4d5060e05c7b4337a3258bb03c4e3ad2f8b15bb/lib_layerdiffusion/models.py#L268

To:
`vis = fg * alpha # + cb * (1 - alpha)`

This way both images will be the transparent image (no checkerboards) and ADetailer will be applied fine. I don't submit a PR with a fix, because I can't test with SDXL, so I don't know how the changes will break other things, but it should not be too complicated to fix. Cheers!

**Comment by protector131090** [comment]
> @layerdiffusion there is a small error around the concatenation of the checkerboard image and the transparent image in the "patch()" function in models.py.
> 
> I noticed it's not only that the wrong image is being saved to the output directory, but also that ADetailer is applied to the wrong image :)
> 
> Cheers!

didnt change anything for me... I mean it did but change is that checkerboard now just pur eblack. Adetailer still dont work with transparent and trasparent wont be saved
